name: Build OpenWrt

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master

on:
  workflow_dispatch:
  # schedule:
  #   - cron: 0 */18 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup OpenWrt build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev gawk git subversion libssl-dev gettext unzip zlib1g-dev file wget

    - name: Get source code
      run: |
        git clone --depth 1 ${{ env.REPO_URL }} -b ${{ env.REPO_BRANCH }} openwrt
        cd openwrt

    - name: Configure build
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cp $FEEDS_CONF feeds.conf.default
        cp $CONFIG_FILE .config

    - name: Run DIY scripts part 1
      run: |
        cd openwrt
        ./diy-part1.sh

    - name: Run DIY scripts part 2
      run: |
        cd openwrt
        ./diy-part2.sh

    - name: Build OpenWrt
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc) V=s
        make -j1 V=s
      continue-on-error: true

    - name: Upload build logs if build fails
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: Build Logs
        path: openwrt/build.log

    - name: Upload firmware
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: OpenWrt Firmware
        path: |
          /home/runner/work/OpenWrt-firmware/OpenWrt-firmware/openwrt/bin/targets/**

    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: jr94330/OpenWrt-firmware
        event-type: Source Code Update

    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 3
        delete_tags: true
        keep_min_download_counts: 0
        delete_expired_data: 0
        delete_prerelease_only: false
        github_rest_api_url: api.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_URL: $REPO_URL
        REPO_BRANCH: $REPO_BRANCH
        FEEDS_CONF: $FEEDS_CONF
        CONFIG_FILE: $CONFIG_FILE
        DIY_P1_SH: $DIY_P1_SH
        DIY_P2_SH: $DIY_P2_SH
        UPLOAD_BIN_DIR: $UPLOAD_BIN_DIR
        UPLOAD_FIRMWARE: $UPLOAD_FIRMWARE
        UPLOAD_RELEASE: $UPLOAD_RELEASE
        TZ: $TZ
        FIRMWARE: $FIRMWARE
